In [1]:
import numpy as np

In [5]:
#1 50-100 хүртэл тоон утга бүхий нэг хэмжээст массив (вектор) үүсгэ. 
a = np.arange(50,100)
print(a)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [6]:
#2 Арван ширхэг 1, арван ширхэг 0, арван ширхэг 6 тоо бүхий нэг хэмжээст массивууд (вектор) үүсгэ.
a=np.ones(10)
b=np.zeros(10)
c=np.ones(10)*6
np.concatenate([a,b,c])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [7]:
#3 20-32 хүртэл тоон утга бүхий 3x4 хэмжээтэй массив үүсгэ.
a=np.arange(20,32).reshape((3,4))
print(a)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [8]:
#4 Диагональ нь 1-ийн тоо, бусад нь 0 байх 3x3 хэмжээтэй массив үүсгэ.
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#5 Диагональ нь 1-5 хүртэл тоо, бусад нь 0 байх 5х5 хэмжээтэй массив үүсгэ.
a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [20]:
#6 Хоёр хэмжээст массив үүсгэж нийт элементүүдийн нийлбэр, багана, мөрийн нийлбэрүүдийг хэвлэ
x=np.array([[1,2],[3,4]])
print(x)
a=np.sum(x)
b=np.sum(x, axis=0)
c=np.sum(x, axis=1)
print("niilber:", a)
print("bagana:", b)
print("mur:",c)

[[1 2]
 [3 4]]
niilber: 10
bagana: [4 6]
mur: [3 7]


In [45]:
#7
x=0
A = np.random.randn(5,5)
B = np.random.randn(5,5)
C = np.random.randn(5,5)
D = np.random.randn(5,5)
E = np.random.randn(5,5)
F = np.random.randn(5,5)
G = np.random.randn(5,5)
H = np.random.randn(5,5)
I = np.random.randn(5,5)
J = np.random.randn(5,5)
a=(A,B,C,D,E,F,G,H,I,J)
b=("A","B","C","D","E","F","G","H","I","J")
for i in a:
    print(b[x])
    x=x+1
    print("column", np.sum(i, axis=0))
    print("row", np.sum(i, axis=1))
    

A
column [-0.92825069  0.96479977 -1.08987828  1.08148293  1.68265149]
row [ 1.36969586 -2.85395381 -0.35509992  2.19800829  1.35215481]
B
column [-0.81542438 -0.54644411  2.01192487  0.82673854 -2.54699515]
row [ 4.52195511 -0.41558647 -2.04522408 -0.88346077 -2.24788402]
C
column [ 0.50158209 -2.65744952 -1.85158127  0.28965035 -3.41139794]
row [-1.8064412   0.40623121 -3.71091588 -2.50439709  0.48632667]
D
column [ 7.68838649 -1.27376302  0.96279525 -0.57093318  3.00225717]
row [ 3.08135181  5.63538285  1.36191364 -1.64016603  1.37026045]
E
column [ 1.98437677 -0.63489298  2.52470969 -0.59811434 -4.23087866]
row [-2.92897048  0.73557344  0.16386488 -0.56468949  1.63942214]
F
column [-2.91382424  3.37438534  4.43988763  0.79157199  3.9368803 ]
row [2.0797143  0.22422478 3.93023445 0.92886219 2.4658653 ]
G
column [-2.40735855 -2.36273249  1.42957325  0.57502747  2.03166576]
row [ 1.95126589 -2.66165343  2.30136833 -4.23095844  1.90615309]
H
column [1.43153039 1.32372692 3.89252077 1.5